---
name: 'Helm Upgrade Release'
description: ''
inputs:
  kubeconfig:
    description: 'kubeconfig file path'
    default: '~/.kube/config'
    required: true
  release:
    description: 'release name'
    required: true
  chart:
    description: 'chart'
    required: true
  namespace:
    description: 'namespace scope'
    required: true
    default: 'default'
  timeout:
    description: 'time to wait for any individual operation'
    required: false
    default: '5m0s'
  values:
    description: 'specify values in a YAML file, or a URL'
    required: false
  set:
    description: 'specify values (coma-separated list)'
    required: false

runs:
  using: 'docker'
  image: 'docker://alpine/helm:3.2.0'
  args:
    - --kubeconfig=${{ input.kubeconfig }}
    - --namespace=${{ input.namespace }}
    - upgrade
    - ${{ input.release }}
    - ${{ input.chart }}
    - --timeout=${{ input.timeout }}
    - --values=${{ input.values }}
    - --set=${{ input.set }}
