---
name: 'Helm Upgrade Release'
description: 'Install or upgrade helm release'
inputs:
  kubeconfig:
    description: 'kubeconfig file path'
    default: '~/.kube/config'
    required: true
  release:
    description: 'release name'
    required: true
  chart:
    description: 'chart'
    required: true
  namespace:
    description: 'namespace scope'
    required: true
    default: 'default'
  timeout:
    description: 'time to wait for any individual operation'
    required: false
    default: '5m0s'
  values:
    description: 'specify values in a YAML file, or a URL'
    required: false
  set:
    description: 'specify values (coma-separated list)'
    required: false

runs:
  using: 'docker'
  image: 'docker://alpine/helm:3.2.0'
  args:
    - --kubeconfig=${{ inputs.kubeconfig }}
    - --namespace=${{ inputs.namespace }}
    - upgrade
    - --install
    - ${{ inputs.release }}
    - ${{ inputs.chart }}
    - --atomic
    - --timeout=${{ inputs.timeout }}
    - --values=${{ inputs.values }}
    - --set=${{ inputs.set }}
